import { Job } from './jobs'

export const MOCK_JOBS: Job[] = [
  {
    id: 'mock-1',
    title: 'Frontend Developer',
    company: 'TechCorp',
    location: 'Remote',
    applyUrl: 'https://careers.google.com',
    salary: '$90k - $120k',
    postedAt: '2 days ago',
    workType: 'remote',
    description: 'Build beautiful, performant web applications using React, TypeScript, and modern CSS. Work with a collaborative team to ship features users love.',
    employmentType: 'Full-time',
    match: 92,
    matchLabel: 'STRONG MATCH',
    applied: false,
    source: 'mock',
  },
  {
    id: 'mock-2',
    title: 'Full Stack Engineer',
    company: 'StartupXYZ',
    location: 'San Francisco, CA',
    applyUrl: 'https://stripe.com/jobs',
    salary: '$110k - $140k',
    postedAt: '1 day ago',
    workType: 'hybrid',
    description: 'Join a fast-growing startup to build the next generation of fintech tools. Experience with Node.js and React preferred.',
    employmentType: 'Full-time',
    match: 85,
    matchLabel: 'STRONG MATCH',
    applied: false,
    source: 'mock',
  },
  {
    id: 'mock-3',
    title: 'React Developer',
    company: 'FinTech Co',
    location: 'Remote',
    applyUrl: 'https://jobs.lever.co',
    salary: '$80k - $100k',
    postedAt: '3 days ago',
    workType: 'remote',
    description: 'Design and implement complex UI components for our trading platform. Strong CSS and accessibility knowledge required.',
    employmentType: 'Full-time',
    match: 78,
    matchLabel: 'GOOD MATCH',
    applied: false,
    source: 'mock',
  },
  {
    id: 'mock-4',
    title: 'Software Engineer II',
    company: 'Acme Inc.',
    location: 'New York, NY',
    applyUrl: 'https://jobs.ashbyhq.com',
    salary: null,
    postedAt: '1 day ago',
    workType: 'hybrid',
    description: 'Work across the full product lifecycle at a well-funded B2B SaaS company. Collaborative culture and strong engineering team.',
    employmentType: 'Full-time',
    match: 74,
    matchLabel: 'GOOD MATCH',
    applied: false,
    source: 'mock',
  },
  {
    id: 'mock-5',
    title: 'Junior Frontend Engineer',
    company: 'GreenTech Startup',
    location: 'Remote',
    applyUrl: 'https://wellfound.com/jobs',
    salary: '$60k - $80k',
    postedAt: '5 hours ago',
    workType: 'remote',
    description: 'Join our mission-driven team building climate tech tools. We invest heavily in mentorship and professional development.',
    employmentType: 'Full-time',
    match: 65,
    matchLabel: 'MATCH',
    applied: false,
    source: 'mock',
  },
]
